### PR TITLE
Fix iptables rules for ICS

### PR DESCRIPTION
**Pull request by KINGSABRI**
Hello Darren, 
Thanks for making this script available. due using this script I found the WifiPineapple NANO still can't connect to internet. I went with lots of confusion first, I thought of using the client AP but that interfere the scanning process. at that moment I reviewed your script deeper and I was sure that the iptables rules are not working properly. 

There are couple of fixes here 

1. Forward must be enabled if the firewall is not in a stateful status (I know you fixed that with `ESTABLISHED,RELATED` but that doesn't give the user an option to open such a decision. since users use pineapple on desktop so it's better to be more specific in these things especially who `DROP` forward connection intentionally )
2. Masquerading better to be more specific to the internet interface (eg. wls1)

In addition, 

- Force **inserting** the rules instead of clear and flushing the existing rules and chains (less destructive)
- I've added some comments to the rules for more clarity (all modern iptables support comments now)

```
iptables -nv -L FORWARD --line-numbers 
Chain FORWARD (policy DROP 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1       14   944 ACCEPT     all  --  enx00c0ca915861 wls1    0.0.0.0/0            0.0.0.0/0            state NEW,RELATED,ESTABLISHED /* WifiPineapple to Inetnet */
2        4   324 ACCEPT     all  --  wls1   enx00c0ca915861  0.0.0.0/0            0.0.0.0/0            state NEW,RELATED,ESTABLISHED /* Internet 2 WifiPineapple */
```

```
iptables -t nat -nv -L POSTROUTING --line-number 
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1     3089  498K MASQUERADE  all  --  *      wls1    0.0.0.0/0            0.0.0.0/0            /* Inetnet Connection Sharing (ICS) */
```

btw, you can make sure `dnsmasq` is installed too! 

**References**
- https://help.ubuntu.com/community/Internet/ConnectionSharing

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Actually, if you don't flush iptables you will insert new rules everytime you connect using this script.
After 4-5 connection you end up with 12-15 repeated lines in iptables

Note: Came from this comment https://forums.hak5.org/topic/41604-wp6sh-setup-fails/?tab=comments#comment-298074
This PR saved my day

**Comment by KINGSABRI** [comment]
> Actually, if you don't flush iptables you will insert new rules everytime you connect using this script.
After 4-5 connection you end up with 12-15 repeated lines in iptables

You're right. We can add a check like 
```
iptables -nv -L FORWARD | grep -i "WifiPineapple to Inetnet"
```
is exist then we skip adding all rules (the forward and natting rules )

Thank you for your feedback

**Comment by H4xl0r** [comment]
Works With the new Kali / the old script not 
Good work thanks

**Review by H4xl0r — APPROVED** [review]

**Comment by sebkinne** [comment]
@KINGSABRI - these changes look good, but ai Agree with @TheZ3ro that we should clean up after ourselves.

If we check using `iptables -nv -L FORWARD | grep -i "WifiPineapple to Inetnet"`, we might have out-of-date rules (ip configuration may have changed).

If there is a good fix for this, I'll gladly accept it and upload it to all relevant locations.

**Comment by KINGSABRI** [comment]
@sebkinne done

**Review by smokephil — APPROVED** [review]

**Comment by eivbsmed** [comment]
This pull request fixes, one of the current issues(#5) and the problems i have been having.
Should be merged soon

**Comment by riveck** [comment]
This indeed solved DNS issues on my Ubuntu 19.04 but only partially. Somehow my interface was showing a different IP than the one that comes by default on the nano:

```
enx00c0caa7cb1c: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.42.194  netmask 255.255.255.0  broadcast 172.16.42.255
        ether 00:c0:ca:a7:cb:1c  txqueuelen 1000  (Ethernet)
        RX packets 2215  bytes 1445895 (1.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2732  bytes 536442 (536.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

That is `172.16.42.194` instead of the expected `172.16.42.42`. I changed the default route on the pineapple -> Networking -> Default route and it all went smoothly from there. Damn that was hard to find!

**Comment by jessefogarty** [comment]
Successfully working on ubuntu 18.04.

IDK why they haven't approved this. I mean the forums are littered with people having the same IPtable issues.

I LOVE YOU!

**Comment by pawiromitchel** [comment]
Thank you!! Why is this pull request not accepted?

**Pull request merged**
